version: '3'
services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: wishlist
      POSTGRES_PASSWORD: wishlist
      POSTGRES_DB: wishlist
    restart: unless-stopped
  mongodb:
    image: mongo
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
  wishlist-service:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET: 9661713c-bef5-4ed4-a3b2-b4c60b09e981
      JWT_EXPIRATION: 3600000
      POSTGRES_URL: jdbc:postgresql://postgres/wishlist
      POSTGRES_USER: wishlist
      POSTGRES_PWD: wishlist
      RABIITMQ_HOST: rabbitmq
      RABIITMQ_PORT: 5672
      RABIITMQ_USER: guest
      RABIITMQ_PWD: guest
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_DB: wishlist




