@baseUrl = http://localhost:8080
@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkdWR1YXJkbzIzQGdtYWlsLmNvbSIsImlhdCI6MTYzNTI4ODkzMSwiZXhwIjoxNjM1MjkyNTMxfQ.usNlhIqQRShUtwKWM9GZrmnceQ-2v0kzhVHzwS7CY2E

# Create new User
POST {{baseUrl}}/api/user
Content-Type: application/json

{
  "name": "Eduardo dos Santos",
  "email": "duduardo23@gmail.com",
  "password": "teste12",
  "confirmPassword": "teste12"
}
###
# Login user
POST {{baseUrl}}/login
Content-Type: application/json

{
  "login": "duduardo23@gmail.com",
  "password": "teste12"
}
###
# Get All user
GET {{baseUrl}}/api/user
Content-Type: application/json
Authorization: Bearer {{token}}

###
# Get User By id
GET {{baseUrl}}/api/user/0cdebc8f-5858-4978-9aa5-eee373ff5103
Content-Type: application/json
Authorization: Bearer {{token}}

###
# Add item to wishlist
POST {{baseUrl}}/api/user/wishlist
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "productId": "79b1c283-00ef-6b22-1c8d-b0721999e2f0"
}
###
# Add item 2 to wishlist
POST {{baseUrl}}/api/user/wishlist
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "productId": "d6d9ab20-ef42-bab5-9b6e-6dc90d981472"
}

###
# Get user wishlist
GET {{baseUrl}}/api/user/wishlist
Content-Type: application/json
Authorization: Bearer {{token}}


###
# Remove item wishlist
DELETE {{baseUrl}}/api/user/wishlist
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "productId": "d6d9ab20-ef42-bab5-9b6e-6dc90d981472"
}



