@baseUrl = http://docker:8080
@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkdWR1YXJkbzIzQGdtYWlsLmNvbSIsImlhdCI6MTYzNTI3OTkxMCwiZXhwIjoxNjM1MjgzNTEwfQ._V-UM7Ozrv-lVJvEoVJI55VvWThHKEBN02zhgOSEYQ0

# Create new User
POST {{baseUrl}}/api/user
Content-Type: application/json

{
  "name": "Eduardo dos Santos",
  "email": "duduardo23@gmail.com",
  "password": "teste12",
  "confirmPassword": "teste12"
}
###
##Login user
POST {{baseUrl}}/login
Content-Type: application/json

{
  "login": "duduardo23@gmail.com",
  "password": "teste12"
}
###
## Get All user
GET {{baseUrl}}/api/user
Content-Type: application/json
Authorization: Bearer {{token}}

###
## Get User By id
GET {{baseUrl}}/api/user/17f6281e-26f6-43e7-b98c-39c60b212ac7
Content-Type: application/json
Authorization: Bearer {{token}}

###
##Add item to wishilist
POST {{baseUrl}}/api/user/wishlist
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "productId": "79b1c283-00ef-6b22-1c8d-b0721999e2f0"
}
###
##Add item 2to wishilist
POST {{baseUrl}}/api/user/wishlist
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "productId": "d6d9ab20-ef42-bab5-9b6e-6dc90d981472"
}

###
##Add item to wishilist
GET {{baseUrl}}/api/user/wishlist
Content-Type: application/json
Authorization: Bearer {{token}}





